version: 1.0.{build}
skip_tags: true
os: Visual Studio 2015
configuration: Release
cache:
 - '%USERPROFILE%\.nuget\packages -> **\project.json'
 - '%APPDATA%\npm-cache -> src\nerdbank-gitversioning.npm\package.json'
init:
- ps: >-
    git config --global user.name appveyor

    git config --global user.email me@appveyor.com
environment:
  VisualStudioVersion: 14.0
install:
- ps: >-
    npm install npm -g
before_build:
- ps: >-
    .\init.ps1

    #$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
- ps: .\build.ps1
artifacts:
- path: bin\**\*.nupkg
- path: bin\js\*.tgz
